# Generated by Django 4.1.3 on 2025-10-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bempatrimonial',
            name='status',
            field=models.CharField(choices=[('aguardando_aprovacao', 'Aguardando aprovação'), ('aprovado', 'Aprovado'), ('nao_aprovado', 'Não aprovado'), ('bloqueado', 'Bloqueado para movimentação')], default='aguardando_aprovacao', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='statusbempatrimonial',
            name='status',
            field=models.CharField(choices=[('aguardando_aprovacao', 'Aguardando aprovação'), ('aprovado', 'Aprovado'), ('nao_aprovado', 'Não aprovado'), ('bloqueado', 'Bloqueado para movimentação')], default='aguardando_aprovacao', max_length=30, verbose_name='Status'),
        ),
    ]
