# Generated by Django 4.1.3 on 2023-03-03 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0001_initial'),
        ('bem_patrimonial', '0002_bempatrimonial_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='bempatrimonial',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Aguardando aprovação'), (2, 'Aprovado'), (3, 'Não aprovado')], default=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='bempatrimonial',
            name='unidade_administrativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dados_comuns.unidadeadministrativa'),
        ),
    ]
