# Generated by Django 4.1.3 on 2025-10-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0002_alter_bempatrimonial_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bempatrimonial',
            name='numero_formato_antigo',
            field=models.BooleanField(default=False, help_text='Se marcado, não valida formato do número (valor livre).', verbose_name='Formato antigo'),
        ),
        migrations.AddField(
            model_name='bempatrimonial',
            name='sem_numeracao',
            field=models.BooleanField(default=False, help_text='Se marcado, o sistema atribui automaticamente', verbose_name='Sem numeração'),
        ),
        migrations.AlterField(
            model_name='bempatrimonial',
            name='numero_patrimonial',
            field=models.CharField(blank=True, db_index=True, help_text='Formato padrão: 000.000000000-0', max_length=15, null=True, unique=True, verbose_name='Número Patrimonial'),
        ),
    ]
