# Generated by Django 4.1.3 on 2025-10-17 19:43

from django.db import migrations, models
from django.db.models import Count, CharField


def deduplicate_numero_patrimonial(apps, schema_editor):
    """
    Deduplica valores de numero_patrimonial ANTES da mudança de schema.
    Se o campo ainda for numérico, evitamos qualquer comparação com ''.
    Mantém o primeiro ID e zera (NULL) os demais duplicados.
    """
    BemPatrimonial = apps.get_model("bem_patrimonial", "BemPatrimonial")

    field = BemPatrimonial._meta.get_field("numero_patrimonial")

    qs_base = BemPatrimonial.objects.exclude(numero_patrimonial__isnull=True)
    if isinstance(field, CharField):

        qs_base = qs_base.exclude(numero_patrimonial="")

    dups = (
        qs_base.values("numero_patrimonial").annotate(cnt=Count("id")).filter(cnt__gt=1)
    )

    for row in dups:
        valor = row["numero_patrimonial"]
        ids = list(
            BemPatrimonial.objects.filter(numero_patrimonial=valor)
            .order_by("id")
            .values_list("id", flat=True)
        )
        drop_ids = ids[1:]
        if drop_ids:
            BemPatrimonial.objects.filter(id__in=drop_ids).update(
                numero_patrimonial=None
            )


class Migration(migrations.Migration):

    dependencies = [
        ("bem_patrimonial", "0002_alter_bempatrimonial_status_and_more"),
    ]

    operations = [
        migrations.RunPython(deduplicate_numero_patrimonial, migrations.RunPython.noop),
        migrations.AddField(
            model_name="bempatrimonial",
            name="numero_formato_antigo",
            field=models.BooleanField(
                default=False,
                help_text="Se marcado, não valida formato do número (valor livre).",
                verbose_name="Formato antigo",
            ),
        ),
        migrations.AddField(
            model_name="bempatrimonial",
            name="sem_numeracao",
            field=models.BooleanField(
                default=False,
                help_text="Se marcado, o sistema atribui automaticamente",
                verbose_name="Sem numeração",
            ),
        ),
        migrations.AlterField(
            model_name="bempatrimonial",
            name="numero_patrimonial",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Formato padrão: 000.000000000-0",
                max_length=15,
                null=True,
                unique=True,
                verbose_name="Número Patrimonial",
            ),
        ),
    ]
