# Generated by Django 4.1.3 on 2025-10-22 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bem_patrimonial', '0003_bempatrimonial_numero_formato_antigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaobempatrimonial',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_canceladopor', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por'),
        ),
        migrations.AlterField(
            model_name='bempatrimonial',
            name='numero_formato_antigo',
            field=models.BooleanField(default=False, help_text='Se marcado, não valida formato do número (valor livre).', verbose_name='Formato anterior'),
        ),
        migrations.AlterField(
            model_name='bempatrimonial',
            name='sem_numeracao',
            field=models.BooleanField(default=False, help_text='Se marcado, o sistema atribui automaticamente', verbose_name='Sem número patrimonial'),
        ),
        migrations.AlterField(
            model_name='movimentacaobempatrimonial',
            name='status',
            field=models.CharField(choices=[('enviada', 'Enviada'), ('aceita', 'Aceita'), ('rejeitada', 'Rejeitada'), ('cancelada_gestor', 'Cancelada pelo Gestor de Patrimônio')], default='enviada', max_length=30, verbose_name='Status'),
        ),
    ]
