# Generated by Django 4.1.3 on 2023-03-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0003_solicitacaomovimentacaobempatrimonial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaomovimentacaobempatrimonial',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
