# Generated by Django 4.1.3 on 2023-03-14 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0004_solicitacaomovimentacaobempatrimonial_quantidade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricoMovimentacaoBemPatrimonial',
        ),
    ]
