# Generated by Django 4.1.3 on 2025-10-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0004_movimentacaobempatrimonial_cancelado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bempatrimonial',
            name='autorizacao_no_doc_em',
        ),
        migrations.RemoveField(
            model_name='bempatrimonial',
            name='data_compra_entrega',
        ),
        migrations.RemoveField(
            model_name='bempatrimonial',
            name='numero_cimbpm',
        ),
        migrations.RemoveField(
            model_name='bempatrimonial',
            name='numero_nibpm',
        ),
        migrations.RemoveField(
            model_name='bempatrimonial',
            name='numero_serie',
        ),
        migrations.RemoveField(
            model_name='bempatrimonial',
            name='origem',
        ),
        migrations.RemoveField(
            model_name='bempatrimonial',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='bempatrimonial',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='bens/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='bempatrimonial',
            name='numero_patrimonial',
            field=models.CharField(blank=True, db_index=True, help_text='Formato padrão: 000.000000000-0', max_length=20, null=True, unique=True, verbose_name='Número Patrimonial'),
        ),
        migrations.AlterField(
            model_name='bempatrimonial',
            name='numero_processo',
            field=models.CharField(max_length=64, verbose_name='Número do processo de incorporação'),
        ),
    ]
