# Generated by Django 4.1.3 on 2023-03-03 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0004_historicostatusbempatrimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicostatusbempatrimonial',
            name='bem_patrimonial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bem_patrimonial.bempatrimonial', verbose_name='Bem patrimonial'),
        ),
    ]
