# Generated by Django 4.1.3 on 2025-10-31 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0004_alter_unidadeadministrativa_options'),
        ('bem_patrimonial', '0005_remove_bempatrimonial_autorizacao_no_doc_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bempatrimonial',
            name='unidade_administrativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bems_patrimonial', to='dados_comuns.unidadeadministrativa'),
        ),
        migrations.DeleteModel(
            name='UnidadeAdministrativaBemPatrimonial',
        ),
    ]
