# Generated by Django 4.1.3 on 2023-03-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0005_historicostatusbempatrimonial_bem_patrimonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicostatusbempatrimonial',
            options={'verbose_name': 'histórico status bem patrimonial', 'verbose_name_plural': 'históricos status bens patrimoniais'},
        ),
    ]
