# Generated by Django 4.1.3 on 2025-11-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0006_alter_bempatrimonial_unidade_administrativa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaobempatrimonial',
            name='quantidade',
        ),
    ]
