# Generated by Django 4.1.3 on 2025-11-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0007_remove_movimentacaobempatrimonial_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaobempatrimonial',
            name='status',
            field=models.CharField(choices=[('enviada', 'Enviada'), ('aceita', 'Aceita'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada')], default='enviada', max_length=30, verbose_name='Status'),
        ),
    ]
