# Generated by Django 4.1.3 on 2023-03-03 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bem_patrimonial', '0007_alter_historicostatusbempatrimonial_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicostatusbempatrimonial',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
    ]
