# Generated by Django 4.1.3 on 2025-11-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0008_alter_movimentacaobempatrimonial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bempatrimonial',
            name='numero_processo',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Número do processo de incorporação'),
        ),
    ]
