# Generated by Django 4.1.3 on 2025-11-06 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0009_alter_bempatrimonial_numero_processo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaobempatrimonial',
            name='numero_cimbpm',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='Número CIMBPM'),
        ),
        migrations.CreateModel(
            name='MovimentacaoBensItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_itens', to='bem_patrimonial.bempatrimonial')),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='bem_patrimonial.movimentacaobempatrimonial')),
            ],
            options={
                'verbose_name': 'item de movimentação',
                'verbose_name_plural': 'itens de movimentação',
            },
        ),
        migrations.AddConstraint(
            model_name='movimentacaobensitem',
            constraint=models.UniqueConstraint(fields=('movimentacao', 'bem'), name='uniq_item_por_movimentacao_bem'),
        ),
    ]
