# Generated by Django 4.1.3 on 2025-11-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bem_patrimonial", "0010_movimentacaobempatrimonial_numero_cimbpm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaobempatrimonial",
            name="documento_cimbpm",
            field=models.FileField(
                blank=True,
                editable=False,
                help_text="PDF gerado automaticamente ao criar movimentação",
                null=True,
                upload_to="documentos_cimbpm/",
                verbose_name="Documento CIMBPM",
            ),
        ),
    ]
