# Generated by Django 4.1.3 on 2025-11-14 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0012_movimentacaobempatrimonial_documento_cimbpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaobempatrimonial',
            name='bens',
            field=models.ManyToManyField(blank=True, related_name='movimentacoes', through='bem_patrimonial.MovimentacaoBensItem', to='bem_patrimonial.bempatrimonial', verbose_name='Bens patrimoniais'),
        ),
        migrations.AlterField(
            model_name='movimentacaobempatrimonial',
            name='bem_patrimonial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bem_patrimonial.bempatrimonial', verbose_name='Bem patrimonial'),
        ),
    ]
