# Generated by Django 4.1.3 on 2025-11-26 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0005_historicogeral_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bem_patrimonial', '0014_popula_movimentacaobensitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaixaFisicaBemPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo_baixa', models.CharField(max_length=64, verbose_name='Número do processo de Baixa Física')),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('aceita', 'Aceita'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada')], default='enviada', max_length=30, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora da solicitação de baixa')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data/hora da aprovação')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baixas_fisicas_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Gestor que aprovou a baixa')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baixas_fisicas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que realizou a baixa')),
                ('unidade_administrativa_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baixas_fisicas_origem', to='dados_comuns.unidadeadministrativa', verbose_name='Unidade administrativa')),
            ],
            options={
                'verbose_name': 'Baixa Física de Bem Patrimonial',
                'verbose_name_plural': 'Baixas Físicas de Bens Patrimoniais',
            },
        ),
        migrations.AlterField(
            model_name='bempatrimonial',
            name='status',
            field=models.CharField(choices=[('aguardando_aprovacao', 'Aguardando aprovação'), ('aprovado', 'Aprovado'), ('nao_aprovado', 'Não aprovado'), ('bloqueado', 'Bloqueado para movimentação'), ('baixa_fisica_aguardando_aprovacao', 'Baixa Física - Aguardando aprovação'), ('baixa_fisica', 'Baixa Física')], default='aguardando_aprovacao', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='statusbempatrimonial',
            name='status',
            field=models.CharField(choices=[('aguardando_aprovacao', 'Aguardando aprovação'), ('aprovado', 'Aprovado'), ('nao_aprovado', 'Não aprovado'), ('bloqueado', 'Bloqueado para movimentação'), ('baixa_fisica_aguardando_aprovacao', 'Baixa Física - Aguardando aprovação'), ('baixa_fisica', 'Baixa Física')], default='aguardando_aprovacao', max_length=50, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='BaixaFisicaBensItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=30, null=True, verbose_name='Status anterior do bem')),
                ('baixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='bem_patrimonial.baixafisicabempatrimonial')),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baixas_fisicas_itens', to='bem_patrimonial.bempatrimonial')),
            ],
            options={
                'verbose_name': 'item de baixa física',
                'verbose_name_plural': 'itens de baixa física',
                'unique_together': {('bem', 'baixa')},
            },
        ),
    ]
