# Generated by Django 4.1.3 on 2025-11-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0015_baixafisicabempatrimonial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baixafisicabempatrimonial',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='baixafisicabensitem',
            name='status_anterior',
        ),
    ]
