# Generated by Django 4.1.3 on 2025-11-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0016_remove_baixafisicabempatrimonial_observacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baixafisicabempatrimonial',
            name='status',
            field=models.CharField(choices=[
                ('aguardando_envio', 'Aguardando envio'),
                ('enviada', 'Enviada'), ('aceita', 'Aceita'), 
                ('rejeitada', 'Rejeitada'), 
                ('cancelada', 'Cancelada')], 
                default='aguardando_envio',
                max_length=30, 
                verbose_name='Status'),
        ),
    ]
