# Generated by Django 4.1.3 on 2025-12-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0017_alter_baixafisicabempatrimonial_status'),
    ]

    operations = [
        # 1. Ajusta o campo STATUS
        migrations.AlterField(
            model_name='baixafisicabempatrimonial',
            name='status',
            field=models.CharField(
                choices=[
                    ('aguardando_envio', 'Aguardando envio'),
                    ('solicitada', 'Solicitada'),
                    ('aceita', 'Aceita'),
                    ('rejeitada', 'Rejeitada'),
                    ('recusada', 'Recusada'),
                ],
                default='aguardando_envio',
                max_length=30,
                verbose_name='Status',
            ),
        ),

        # 2. Atualiza todos que tinham status "enviada" → "solicitada"
        migrations.RunSQL(
            """
            UPDATE bem_patrimonial_baixafisicabempatrimonial
            SET status = 'solicitada'
            WHERE status = 'enviada';
            """,
            reverse_sql="""
            UPDATE bem_patrimonial_baixafisicabempatrimonial
            SET status = 'enviada'
            WHERE status = 'solicitada';
            """
        ),
    ]