# Generated by Django 4.1.3 on 2025-12-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0018_alter_baixafisicabempatrimonial_status'),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE bem_patrimonial_baixafisicabempatrimonial
            SET status = 'recusada'
            WHERE status = 'cancelada';
            """,
            reverse_sql="""
            UPDATE bem_patrimonial_baixafisicabempatrimonial
            SET status = 'recusada'
            WHERE status = 'cancelada';
            """
        ),
    ]