# Generated by Django 4.1.3 on 2025-12-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0020_bempatrimonial_bloqueado_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baixafisicabempatrimonial',
            name='status',
            field=models.CharField(choices=[('aguardando_envio', 'Aguardando envio'), ('solicitada', 'Solicitada'), ('aceita', 'Aceita'), ('recusada', 'Recusada')], default='aguardando_envio', max_length=30, verbose_name='Status'),
        ),
    ]
