# Generated by Django 4.1.3 on 2025-12-29 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0021_alter_baixafisicabempatrimonial_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='baixafisicabempatrimonial',
            name='data_baixa',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data informada no processo de baixa física', verbose_name='Data da Baixa Física'),
        ),
    ]
