# Generated by Django 4.1.3 on 2026-01-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0022_baixafisicabempatrimonial_data_baixa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bempatrimonial',
            name='bloqueado_inventario',
        ),
        migrations.AddField(
            model_name='bempatrimonial',
            name='bloqueado_conciliacao',
            field=models.BooleanField(default=False, help_text='Se True, bem não pode ser movimentado até atualização de situação na consiliaçãp', verbose_name='Bloqueado por inventário'),
        ),
    ]
