# Generated by Django 4.1.3 on 2026-01-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0023_remove_bempatrimonial_bloqueado_inventario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaobempatrimonial',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
    ]
