# Generated by Django 4.1.3 on 2026-01-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0024_alter_movimentacaobempatrimonial_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='bempatrimonial',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bempatrimonial',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='bempatrimonial',
            name='numero_patrimonial',
            field=models.CharField(blank=True, db_index=True, help_text='Formato padrão: 000.000000000-0', max_length=20, null=True, verbose_name='Número Patrimonial'),
        ),
        migrations.AddConstraint(
            model_name='bempatrimonial',
            constraint=models.UniqueConstraint(condition=models.Q(('excluido', False)), fields=('numero_patrimonial',), name='uniq_numero_patrimonial_ativo'),
        ),
    ]
