# Generated by Django 4.1.3 on 2026-01-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0025_bempatrimonial_excluido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baixafisicabempatrimonial',
            name='numero_nbbpm',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
