# Generated by Django 4.1.3 on 2026-02-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0026_baixafisicabempatrimonial_numero_nbbpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='bempatrimonial',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='bempatrimonial',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
