# Generated by Django 4.1.3 on 2026-02-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0030_fix_mov_status_observacao_not_null'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bempatrimonial',
            name='uniq_numero_patrimonial_ativo',
        ),
        migrations.AlterField(
            model_name='baixafisicabempatrimonial',
            name='numero_nbbpm',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='bempatrimonial',
            name='localizacao',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='bempatrimonial',
            name='numero_patrimonial',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Formato padrão: 000.000000000-0', max_length=20, verbose_name='Número Patrimonial'),
        ),
        migrations.AlterField(
            model_name='bempatrimonial',
            name='numero_processo',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Número do processo de incorporação'),
        ),
        migrations.AlterField(
            model_name='movimentacaobempatrimonial',
            name='documento_cimbpm',
            field=models.FileField(blank=True, default='', editable=False, help_text='PDF gerado automaticamente ao criar movimentação', upload_to='documentos_cimbpm/', verbose_name='Documento CIMBPM'),
        ),
        migrations.AlterField(
            model_name='movimentacaobempatrimonial',
            name='numero_cimbpm',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30, unique=True, verbose_name='Número CIMBPM'),
        ),
        migrations.AddConstraint(
            model_name='bempatrimonial',
            constraint=models.UniqueConstraint(condition=models.Q(('excluido', False), models.Q(('numero_patrimonial', ''), _negated=True)), fields=('numero_patrimonial',), name='uniq_numero_patrimonial_ativo'),
        ),
    ]
