# Generated by Django 4.1.3 on 2026-06-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0041_remove_unique_numero_processo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baixafisicabempatrimonial',
            name='data_baixa',
            field=models.DateField(blank=True, help_text='Data informada no processo de baixa física', null=True, verbose_name='Data da Baixa Física'),
        ),
        migrations.AlterField(
            model_name='baixafisicabempatrimonial',
            name='numero_processo_baixa',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Número do processo de Baixa Física'),
        ),
        migrations.AlterField(
            model_name='baixafisicabempatrimonial',
            name='status',
            field=models.CharField(choices=[('aguardando_envio', 'Em elaboração'), ('solicitada', 'Solicitada'), ('aceita', 'Aceita'), ('recusada', 'Recusada')], default='aguardando_envio', max_length=30, verbose_name='Status'),
        ),
    ]
