# Generated by Django 4.1.3 on 2026-07-01 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bem_patrimonial', '0042_alter_baixafisicabempatrimonial_data_baixa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NBBPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, db_index=True, default='', help_text='Gerado automaticamente, no formato <COD_UO>.<SEQUENCIAL_7>.<ANO>', max_length=32, verbose_name='Número da NBBPM')),
                ('numero_processo_baixa', models.CharField(max_length=64, verbose_name='Número do processo de Baixa')),
                ('data_autorizacao', models.DateField(verbose_name='Data da Autorização')),
                ('responsavel', models.CharField(max_length=255, verbose_name='Responsável')),
                ('numero_processo_destinacao_final', models.CharField(blank=True, default='', max_length=64, verbose_name='Número do processo de destinação final')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de geração')),
                ('baixas', models.ManyToManyField(related_name='nbbpms_lote', to='bem_patrimonial.baixafisicabempatrimonial', verbose_name='Baixas Físicas')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nbbpms_lote_geradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que gerou a NBBPM')),
            ],
            options={
                'verbose_name': 'NBBPM (Nota de Baixa de Bens Patrimoniais Móveis e Intangíveis)',
                'verbose_name_plural': 'NBBPMs (Notas de Baixa de Bens Patrimoniais Móveis e Intangíveis)',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
