# Generated by Django 5.2.15 on 2026-08-26 17:23 — reescrito para prefixo fixo 001, sequencial global por ano, escopo por UO
import django.core.validators
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q
from django.db.models.functions import Substr

PREFIXO_FIXO = "001"


def migrar_baixa_para_nbbpm(apps, schema_editor):
    Baixa = apps.get_model("bem_patrimonial", "BaixaFisicaBemPatrimonial")
    NBBPM = apps.get_model("bem_patrimonial", "NBBPM")
    Usuario = apps.get_model("usuario", "Usuario")
    db_alias = schema_editor.connection.alias

    baixas_com_numero = Baixa.objects.using(db_alias).filter(
        numero_nbbpm__isnull=False
    ).exclude(numero_nbbpm__exact="").exclude(numero_nbbpm__exact=None)

    for baixa in baixas_com_numero.iterator():
        numero = (baixa.numero_nbbpm or "").strip()
        if not numero:
            continue
        if NBBPM.objects.using(db_alias).filter(numero=numero).exists():
            try:
                nbbpm_existente = NBBPM.objects.using(db_alias).filter(numero=numero).first()
                if nbbpm_existente and not nbbpm_existente.baixas.filter(pk=baixa.pk).exists():
                    nbbpm_existente.baixas.add(baixa)
            except Exception:
                pass
            continue

        num_proc = (getattr(baixa, "numero_processo_baixa", "") or "").strip()
        if not num_proc:
            num_proc = f"BAIXA-{baixa.pk}"

        data_aut = None
        if getattr(baixa, "data_aprovacao", None):
            try:
                data_aut = baixa.data_aprovacao.date() if hasattr(baixa.data_aprovacao, "date") else baixa.data_aprovacao
            except Exception:
                data_aut = None
        if not data_aut:
            data_aut = getattr(baixa, "data_baixa", None)
        if not data_aut:
            from django.utils import timezone
            data_aut = timezone.now().date()

        responsavel = "SISTEMA"
        criado_por_id = None
        try:
            if getattr(baixa, "aprovado_por_id", None):
                try:
                    u = Usuario.objects.using(db_alias).get(pk=baixa.aprovado_por_id)
                    responsavel = getattr(u, "username", None) or responsavel
                    criado_por_id = u.pk
                except Usuario.DoesNotExist:
                    pass
            if not criado_por_id and getattr(baixa, "criado_por_id", None):
                try:
                    u2 = Usuario.objects.using(db_alias).get(pk=baixa.criado_por_id)
                    if responsavel == "SISTEMA":
                        responsavel = getattr(u2, "username", None) or responsavel
                    criado_por_id = u2.pk
                except Usuario.DoesNotExist:
                    pass
        except Exception:
            pass

        if not criado_por_id:
            try:
                first_user = Usuario.objects.using(db_alias).first()
                if first_user:
                    criado_por_id = first_user.pk
                    if responsavel == "SISTEMA":
                        responsavel = getattr(first_user, "username", "SISTEMA")
                else:
                    continue
            except Exception:
                continue

        try:
            nbbpm = NBBPM.objects.using(db_alias).create(
                numero=numero,
                numero_processo_baixa=num_proc,
                data_autorizacao=data_aut,
                responsavel=responsavel[:255],
                numero_processo_destinacao_final="",
                criado_por_id=criado_por_id,
            )
            nbbpm.baixas.add(baixa)
        except Exception:
            continue

    try:
        baixas_sem_numero = Baixa.objects.using(db_alias).filter(
            status="aceita"
        ).filter(
            Q(numero_nbbpm__isnull=True) | Q(numero_nbbpm__exact="")
        )
        for baixa in baixas_sem_numero.iterator():
            if NBBPM.objects.using(db_alias).filter(baixas__in=[baixa]).exists():
                continue
            # prefixo fixo 001, sequencial global por ano
            prefixo = PREFIXO_FIXO
            data_aut = None
            if getattr(baixa, "data_aprovacao", None):
                try:
                    data_aut = baixa.data_aprovacao.date() if hasattr(baixa.data_aprovacao, "date") else baixa.data_aprovacao
                except Exception:
                    data_aut = None
            if not data_aut:
                data_aut = getattr(baixa, "data_baixa", None)
            if not data_aut:
                from django.utils import timezone
                data_aut = timezone.now().date()
            ano = data_aut.year if hasattr(data_aut, "year") else 2026

            from django.db.models import IntegerField, Max, Value
            from django.db.models.functions import Cast, Replace, Substr
            # considera tanto "." quanto "/" antes do ano para compatibilidade
            qs_nbbpm = NBBPM.objects.using(db_alias).filter(numero__startswith=f"{prefixo}.").filter(Q(numero__endswith=f".{ano}") | Q(numero__endswith=f"/{ano}")).exclude(numero__exact="")
            try:
                seq_raw = Substr("numero", 5, 7)
                seq_digits = Replace(seq_raw, Value("."), Value(""))
                seq_digits = Replace(seq_digits, Value("/"), Value(""))
                max_nbbpm = qs_nbbpm.annotate(seq_int=Cast(seq_digits, IntegerField())).aggregate(m=Max("seq_int"))["m"] or 0
            except Exception:
                max_nbbpm = 0
            qs_baixa = Baixa.objects.using(db_alias).filter(
                numero_nbbpm__startswith=f"{prefixo}.",
                numero_nbbpm__isnull=False,
            ).exclude(numero_nbbpm__exact="").filter(Q(numero_nbbpm__endswith=f".{ano}") | Q(numero_nbbpm__endswith=f"/{ano}"))
            try:
                seq_raw2 = Substr("numero_nbbpm", 5, 7)
                seq_digits2 = Replace(seq_raw2, Value("."), Value(""))
                seq_digits2 = Replace(seq_digits2, Value("/"), Value(""))
                max_baixa = qs_baixa.annotate(seq_int=Cast(seq_digits2, IntegerField())).aggregate(m=Max("seq_int"))["m"] or 0
            except Exception:
                max_baixa = 0
            proximo = max(max_nbbpm, max_baixa) + 1
            numero_novo = f"{prefixo}.{proximo:07d}/{ano}"

            if NBBPM.objects.using(db_alias).filter(numero=numero_novo).exists():
                proximo += 1
                numero_novo = f"{prefixo}.{proximo:07d}/{ano}"
                if NBBPM.objects.using(db_alias).filter(numero=numero_novo).exists():
                    continue

            num_proc = (getattr(baixa, "numero_processo_baixa", "") or "").strip() or f"BAIXA-{baixa.pk}"
            responsavel = "SISTEMA"
            criado_por_id = getattr(baixa, "aprovado_por_id", None) or getattr(baixa, "criado_por_id", None)
            if not criado_por_id:
                try:
                    fu = Usuario.objects.using(db_alias).first()
                    if fu:
                        criado_por_id = fu.pk
                        responsavel = getattr(fu, "username", "SISTEMA")
                except Exception:
                    continue
            else:
                try:
                    u = Usuario.objects.using(db_alias).get(pk=criado_por_id)
                    responsavel = getattr(u, "username", "SISTEMA")
                except Exception:
                    pass

            try:
                nbbpm2 = NBBPM.objects.using(db_alias).create(
                    numero=numero_novo,
                    numero_processo_baixa=num_proc,
                    data_autorizacao=data_aut,
                    responsavel=responsavel[:255],
                    numero_processo_destinacao_final="",
                    criado_por_id=criado_por_id,
                )
                nbbpm2.baixas.add(baixa)
                try:
                    Baixa.objects.using(db_alias).filter(pk=baixa.pk).update(numero_nbbpm=numero_novo)
                except Exception:
                    pass
            except Exception:
                continue
    except Exception:
        pass


def reverse_migracao(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bem_patrimonial', '0043_nbbpm'),
        ('dados_comuns', '0007_vincular_uo_padrao_em_uas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nbbpm',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'NBBPM', 'verbose_name_plural': 'NBBPMs'},
        ),
        migrations.AlterField(
            model_name='baixafisicabempatrimonial',
            name='numero_nbbpm',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, help_text='Campo legado desativado para escrita; consultar NBBPM via M2M.', max_length=32),
        ),
        migrations.AlterField(
            model_name='nbbpm',
            name='numero',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Gerado automaticamente, no formato 001.<SEQUENCIAL_7>/<ANO>', max_length=32, validators=[django.core.validators.RegexValidator(message='Número NBBPM deve estar no formato 001.YYYYYYY/ZZZZ', regex='^\\d{3}\\.\\d{7}[\\./]\\d{4}$')], verbose_name='Número da NBBPM'),
        ),
        migrations.AddIndex(
            model_name='nbbpm',
            index=models.Index(fields=['numero'], name='bem_patrimo_numero_b790aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='nbbpm',
            constraint=models.UniqueConstraint(condition=models.Q(('numero__isnull', False), models.Q(('numero', ''), _negated=True)), fields=('numero',), name='uniq_nbbpm_numero'),
        ),
        migrations.AddIndex(
            model_name='nbbpm',
            index=models.Index(Substr('numero', 5, 7), name='idx_nbbpm_numero_substr'),
        ),
        migrations.RunPython(migrar_baixa_para_nbbpm, reverse_migracao),
    ]
