# Generated by Django 4.1.3 on 2025-12-08 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dados_comuns', '0005_historicogeral_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bem_patrimonial', '0020_bempatrimonial_bloqueado_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioUA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inventario', models.CharField(help_text='Formato: 001.XXXX/AAAA (auto-gerado)', max_length=30, unique=True, verbose_name='Número do Inventário')),
                ('ano_referencia', models.PositiveSmallIntegerField(help_text='Ano ao qual o inventário se refere', verbose_name='Ano de Referência')),
                ('tipo', models.CharField(choices=[('anual', 'Anual'), ('eventual', 'Eventual')], default='anual', max_length=20, verbose_name='Tipo')),
                ('vigencia', models.DateField(help_text='Data limite para finalização (padrão: 31/12/ano_referencia)', verbose_name='Vigência')),
                ('status', models.CharField(choices=[('em_aberto', 'Em aberto'), ('fechado', 'Fechado')], default='em_aberto', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('fechado_em', models.DateTimeField(blank=True, null=True, verbose_name='Fechado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_fechados', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por')),
                ('unidade_administrativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='dados_comuns.unidadeadministrativa', verbose_name='Unidade Administrativa')),
            ],
            options={
                'verbose_name': 'Inventário de UA',
                'verbose_name_plural': 'Inventários de UA',
                'ordering': ['-ano_referencia', 'unidade_administrativa'],
                'unique_together': {('unidade_administrativa', 'ano_referencia')},
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('encontrado_sem_divergencia', 'Encontrado sem divergência'), ('encontrado', 'Encontrado'), ('nao_encontrado', 'Não encontrado'), ('divergente', 'Divergente'), ('baixa_fisica', 'Baixa Física')], default='encontrado_sem_divergencia', max_length=30, verbose_name='Situação')),
                ('situacao_anterior', models.CharField(blank=True, choices=[('encontrado_sem_divergencia', 'Encontrado sem divergência'), ('encontrado', 'Encontrado'), ('nao_encontrado', 'Não encontrado'), ('divergente', 'Divergente'), ('baixa_fisica', 'Baixa Física')], help_text='Situação no inventário do ano anterior', max_length=30, null=True, verbose_name='Situação Anterior')),
                ('observacao', models.TextField(blank=True, help_text='Observações sobre o item (opcional)', verbose_name='Observação')),
                ('divergencia', models.TextField(blank=True, help_text='Descrição da divergência encontrada (obrigatório quando situação = Divergente)', verbose_name='Divergência')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('bem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_inventario', to='bem_patrimonial.bempatrimonial', verbose_name='Bem Patrimonial')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='inventario.inventarioua', verbose_name='Inventário')),
            ],
            options={
                'verbose_name': 'Item de Inventário',
                'verbose_name_plural': 'Itens de Inventário',
                'ordering': ['bem__numero_patrimonial'],
                'unique_together': {('inventario', 'bem')},
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao_anterior', models.CharField(help_text='Situação antes da mudança', max_length=30, verbose_name='Situação Anterior')),
                ('situacao_nova', models.CharField(help_text='Nova situação após mudança', max_length=30, verbose_name='Situação Nova')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('divergencia', models.TextField(blank=True, verbose_name='Divergência')),
                ('registrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='inventario.iteminventario', verbose_name='Item de Inventário')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Ocorrência de Inventário',
                'verbose_name_plural': 'Ocorrências de Inventário',
                'ordering': ['-registrado_em'],
            },
        ),
    ]
