# Generated by Django 4.1.3 on 2025-12-12 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0005_historicogeral_and_more'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventarioua',
            options={'ordering': ['-periodo_inicial', 'unidade_administrativa', '-criado_em'], 'verbose_name': 'Gerenciamento de Inventário', 'verbose_name_plural': 'Gerenciamento de Inventário'},
        ),
        migrations.AlterUniqueTogether(
            name='inventarioua',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='iteminventario',
            name='situacao_anterior',
        ),
        migrations.RemoveField(
            model_name='ocorrenciainventario',
            name='situacao_anterior',
        ),
        migrations.RemoveField(
            model_name='ocorrenciainventario',
            name='situacao_nova',
        ),
        migrations.AddField(
            model_name='inventarioua',
            name='periodo_final',
            field=models.DateField(default=datetime.date.today, help_text='Data final do período do inventário', verbose_name='Período Final'),
        ),
        migrations.AddField(
            model_name='inventarioua',
            name='periodo_inicial',
            field=models.DateField(default=datetime.date.today, help_text='Data inicial do período do inventário', verbose_name='Período Inicial'),
        ),
        migrations.AddField(
            model_name='ocorrenciainventario',
            name='situacao',
            field=models.CharField(choices=[('encontrado_sem_divergencia', 'Encontrado sem divergência'), ('encontrado', 'Encontrado'), ('nao_encontrado', 'Não encontrado'), ('divergente', 'Divergente'), ('baixa_fisica', 'Baixa Física')], default='encontrado_sem_divergencia', help_text='Situação na ocorrencia', max_length=30, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='inventarioua',
            name='numero_inventario',
            field=models.CharField(help_text='Formato: 001.XXXX/AAAA (anual) ou 001.XXXX/AAAA/VVV (eventual)', max_length=30, unique=True, verbose_name='Número do Inventário'),
        ),
        migrations.AlterField(
            model_name='inventarioua',
            name='tipo',
            field=models.CharField(choices=[('anual', 'Anual'), ('eventual', 'Eventual')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='divergencia',
            field=models.TextField(blank=True, help_text='Descrição da divergência (obrigatório quando situação = Divergente)', verbose_name='Divergência'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='situacao',
            field=models.CharField(choices=[('encontrado_sem_divergencia', 'Encontrado sem divergência'), ('encontrado', 'Encontrado'), ('nao_encontrado', 'Não encontrado'), ('divergente', 'Divergente'), ('baixa_fisica', 'Baixa Física')], help_text='Situação do bem no momento da criação do inventário', max_length=30, verbose_name='Situação'),
        ),
        migrations.AlterUniqueTogether(
            name='inventarioua',
            unique_together={('unidade_administrativa', 'tipo', 'periodo_inicial', 'periodo_final')},
        ),
        migrations.AddIndex(
            model_name='inventarioua',
            index=models.Index(fields=['unidade_administrativa', 'periodo_inicial'], name='inventario__unidade_3c1d68_idx'),
        ),
        migrations.AddIndex(
            model_name='inventarioua',
            index=models.Index(fields=['unidade_administrativa', 'tipo', 'periodo_inicial'], name='inventario__unidade_0021cb_idx'),
        ),
        migrations.AddIndex(
            model_name='iteminventario',
            index=models.Index(fields=['inventario', 'bem'], name='inventario__inventa_fcf1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='iteminventario',
            index=models.Index(fields=['bem'], name='inventario__bem_id_f5eeaf_idx'),
        ),
        migrations.AddIndex(
            model_name='iteminventario',
            index=models.Index(fields=['situacao'], name='inventario__situaca_4259a4_idx'),
        ),
        migrations.AddIndex(
            model_name='ocorrenciainventario',
            index=models.Index(fields=['item', 'registrado_em'], name='inventario__item_id_272501_idx'),
        ),
        migrations.RemoveField(
            model_name='inventarioua',
            name='ano_referencia',
        ),
        migrations.RemoveField(
            model_name='inventarioua',
            name='vigencia',
        ),
    ]
