# Generated by Django 4.1.3 on 2025-12-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0005_historicogeral_and_more'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventarioua',
            options={'ordering': ['-ano_referencia', 'unidade_administrativa', '-versao'], 'verbose_name': 'Inventário de UA', 'verbose_name_plural': 'Inventários de UA'},
        ),
        migrations.AlterUniqueTogether(
            name='inventarioua',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventarioua',
            name='versao',
            field=models.PositiveSmallIntegerField(default=1, help_text='Versão do inventário (usado apenas para inventários eventuais)', verbose_name='Versão'),
        ),
        migrations.AlterField(
            model_name='inventarioua',
            name='numero_inventario',
            field=models.CharField(help_text='Formato: 001.XXXX/AAAA (anual) ou 001.XXXX/AAAA/VVV (eventual)', max_length=30, unique=True, verbose_name='Número do Inventário'),
        ),
        migrations.AlterUniqueTogether(
            name='inventarioua',
            unique_together={('unidade_administrativa', 'ano_referencia', 'tipo', 'versao')},
        ),
    ]
