# Generated by Django 4.1.3 on 2025-12-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0005_historicogeral_and_more'),
        ('inventario', '0002_add_versao_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroInventarioAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_referencia', models.PositiveSmallIntegerField(help_text='Ano do inventário anual ao qual este parâmetro se refere (ex.: 2025).', verbose_name='Ano de Referência')),
                ('periodo_inicial', models.DateField(help_text='Data inicial em que inventários anuais podem ser criados/fechados.', verbose_name='Período Inicial Permitido')),
                ('periodo_final', models.DateField(help_text='Data final em que inventários anuais podem ser criados/fechados.', verbose_name='Período Final Permitido')),
                ('ativo', models.BooleanField(default=True, help_text='Apenas um parâmetro ativo por ano.', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Parâmetro de Inventário Anual',
                'verbose_name_plural': 'Parâmetros de Inventário Anual',
            },
        ),
        migrations.AlterModelOptions(
            name='inventarioua',
            options={'ordering': ['-periodo_inicial', 'unidade_administrativa', '-criado_em'], 'verbose_name': 'Gerenciamento de Inventário', 'verbose_name_plural': 'Gerenciamento de Inventário'},
        ),
        migrations.AlterUniqueTogether(
            name='inventarioua',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='iteminventario',
            name='situacao_anterior',
        ),
        migrations.RemoveField(
            model_name='ocorrenciainventario',
            name='situacao_anterior',
        ),
        migrations.RemoveField(
            model_name='ocorrenciainventario',
            name='situacao_nova',
        ),
        migrations.AddField(
            model_name='inventarioua',
            name='periodo_final',
            field=models.DateField(help_text='Data final do período do inventário.', null=True, verbose_name='Período Final'),
        ),
        migrations.AddField(
            model_name='inventarioua',
            name='periodo_inicial',
            field=models.DateField(help_text='Data inicial do período do inventário (define o ano base do número).', null=True, verbose_name='Período Inicial'),
        ),
        migrations.AddField(
            model_name='ocorrenciainventario',
            name='situacao',
            field=models.CharField(choices=[('encontrado_sem_divergencia', 'Encontrado sem divergência'), ('encontrado', 'Encontrado'), ('nao_encontrado', 'Não encontrado'), ('divergente', 'Divergente'), ('baixa_fisica', 'Baixa Física')], default='encontrado_sem_divergencia', help_text='Situação na ocorrência', max_length=30, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='inventarioua',
            name='tipo',
            field=models.CharField(choices=[('anual', 'Anual'), ('eventual', 'Eventual')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='divergencia',
            field=models.TextField(blank=True, help_text='Descrição da divergência (obrigatório quando situação = Divergente)', verbose_name='Divergência'),
        ),
        migrations.AlterField(
            model_name='iteminventario',
            name='situacao',
            field=models.CharField(choices=[('encontrado_sem_divergencia', 'Encontrado sem divergência'), ('encontrado', 'Encontrado'), ('nao_encontrado', 'Não encontrado'), ('divergente', 'Divergente'), ('baixa_fisica', 'Baixa Física')], default='encontrado_sem_divergencia', help_text='Situação do bem no momento da criação do inventário', max_length=30, verbose_name='Situação'),
        ),
        migrations.AlterUniqueTogether(
            name='inventarioua',
            unique_together={('unidade_administrativa', 'tipo', 'periodo_inicial', 'periodo_final')},
        ),
        migrations.AddIndex(
            model_name='inventarioua',
            index=models.Index(fields=['unidade_administrativa', 'periodo_inicial'], name='inventario__unidade_3c1d68_idx'),
        ),
        migrations.AddIndex(
            model_name='inventarioua',
            index=models.Index(fields=['unidade_administrativa', 'tipo', 'periodo_inicial'], name='inventario__unidade_0021cb_idx'),
        ),
        migrations.AddIndex(
            model_name='iteminventario',
            index=models.Index(fields=['inventario', 'bem'], name='inventario__inventa_fcf1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='iteminventario',
            index=models.Index(fields=['bem'], name='inventario__bem_id_f5eeaf_idx'),
        ),
        migrations.AddIndex(
            model_name='iteminventario',
            index=models.Index(fields=['situacao'], name='inventario__situaca_4259a4_idx'),
        ),
        migrations.AddIndex(
            model_name='ocorrenciainventario',
            index=models.Index(fields=['item', 'registrado_em'], name='inventario__item_id_272501_idx'),
        ),
        migrations.AddConstraint(
            model_name='parametroinventarioanual',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('ano_referencia',), name='unique_parametro_inventario_anual_ativo_por_ano'),
        ),
        migrations.RemoveField(
            model_name='inventarioua',
            name='ano_referencia',
        ),
        migrations.RemoveField(
            model_name='inventarioua',
            name='versao',
        ),
        migrations.RemoveField(
            model_name='inventarioua',
            name='vigencia',
        ),
    ]
