# Generated by Django 4.1.3 on 2025-12-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_parametroinventarioanual_alter_inventarioua_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventarioua',
            options={'ordering': ['-criado_em', 'unidade_administrativa'], 'verbose_name': 'Gerenciamento de Inventário', 'verbose_name_plural': 'Gerenciamento de Inventário'},
        ),
        migrations.RemoveIndex(
            model_name='inventarioua',
            name='inventario__unidade_3c1d68_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventarioua',
            name='inventario__unidade_0021cb_idx',
        ),
        migrations.AlterUniqueTogether(
            name='inventarioua',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='inventarioua',
            index=models.Index(fields=['unidade_administrativa', 'tipo'], name='inventario__unidade_6b4dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='inventarioua',
            index=models.Index(fields=['unidade_administrativa', 'periodo_final'], name='inventario__unidade_52550d_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventarioua',
            constraint=models.UniqueConstraint(fields=('unidade_administrativa', 'tipo', 'periodo_final'), name='uniq_inventario_ua_tipo_periodo_final'),
        ),
        migrations.RemoveField(
            model_name='inventarioua',
            name='periodo_inicial',
        ),
    ]
