# Generated by Django 4.1.3 on 2025-12-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_inventarioua_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioua',
            name='periodo_final',
            field=models.DateField(blank=True, help_text='Data final do período do inventário.', null=True, verbose_name='Período Final'),
        ),
        migrations.AlterField(
            model_name='ocorrenciainventario',
            name='situacao',
            field=models.CharField(choices=[('encontrado_sem_divergencia', 'Encontrado sem divergência'), ('encontrado', 'Encontrado'), ('nao_encontrado', 'Não encontrado'), ('divergente', 'Divergente'), ('baixa_fisica', 'Baixa Física')], default='divergente', help_text='Situação na ocorrencia', max_length=30, verbose_name='Situação'),
        ),
    ]
