# Generated by Django 4.1.3 on 2025-12-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_inventarioua_periodo_final_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametroinventarioanual',
            options={'ordering': ['-ano_referencia', '-periodo_inicial'], 'verbose_name': 'Parâmetro de Inventário Anual', 'verbose_name_plural': 'Parâmetros de Inventário Anual'},
        ),
    ]
