# Generated by Django 4.1.3 on 2026-01-02 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dados_comuns', '0005_historicogeral_and_more'),
        ('bem_patrimonial', '0022_baixafisicabempatrimonial_data_baixa'),
        ('inventario', '0009_ajustes_verbose_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conciliacaoua',
            options={'ordering': ['-criado_em', 'unidade_administrativa'], 'verbose_name': 'Gerenciamento de Conciliação', 'verbose_name_plural': 'Gerenciamento de Conciliação'},
        ),
        migrations.AlterModelOptions(
            name='itemconciliacao',
            options={'ordering': ['bem__numero_patrimonial'], 'verbose_name': 'Item de Conciliação', 'verbose_name_plural': 'Itens de Conciliação'},
        ),
        migrations.AlterModelOptions(
            name='ocorrenciaconciliacao',
            options={'ordering': ['-registrado_em'], 'verbose_name': 'Ocorrência de Conciliação', 'verbose_name_plural': 'Ocorrências de Conciliação'},
        ),
        migrations.AlterModelOptions(
            name='parametroconciliacaoanual',
            options={'ordering': ['-ano_referencia', '-periodo_inicial'], 'verbose_name': 'Parâmetro de Conciliação Anual', 'verbose_name_plural': 'Parâmetros de Conciliação Anual'},
        ),
        migrations.RemoveConstraint(
            model_name='conciliacaoua',
            name='uniq_inventario_ua_tipo_periodo_final',
        ),
        migrations.RemoveConstraint(
            model_name='parametroconciliacaoanual',
            name='unique_parametro_inventario_anual_ativo_por_ano',
        ),
        migrations.RemoveIndex(
            model_name='itemconciliacao',
            name='inventario__inventa_fcf1e9_idx',
        ),
        migrations.RenameIndex(
            model_name='conciliacaoua',
            new_name='inventario__unidade_163940_idx',
            old_name='inventario__unidade_6b4dd3_idx',
        ),
        migrations.RenameIndex(
            model_name='conciliacaoua',
            new_name='inventario__unidade_db5b03_idx',
            old_name='inventario__unidade_52550d_idx',
        ),
        migrations.RenameIndex(
            model_name='itemconciliacao',
            new_name='inventario__bem_id_b21535_idx',
            old_name='inventario__bem_id_f5eeaf_idx',
        ),
        migrations.RenameIndex(
            model_name='itemconciliacao',
            new_name='inventario__situaca_078c9a_idx',
            old_name='inventario__situaca_4259a4_idx',
        ),
        migrations.RenameIndex(
            model_name='ocorrenciaconciliacao',
            new_name='inventario__item_id_b136d1_idx',
            old_name='inventario__item_id_272501_idx',
        ),
        migrations.AlterField(
            model_name='conciliacaoua',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='conciliacaoua',
            name='fechado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes_fechadas', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por'),
        ),
        migrations.AlterField(
            model_name='conciliacaoua',
            name='numero_conciliacao',
            field=models.CharField(help_text='Formato: 001.XXXX/AAAA (anual) ou 001.XXXX/AAAA/VVV (eventual)', max_length=30, unique=True, verbose_name='Número do Conciliação'),
        ),
        migrations.AlterField(
            model_name='conciliacaoua',
            name='unidade_administrativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes', to='dados_comuns.unidadeadministrativa', verbose_name='Unidade Administrativa'),
        ),
        migrations.AlterField(
            model_name='itemconciliacao',
            name='bem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_conciliacao', to='bem_patrimonial.bempatrimonial', verbose_name='Bem Patrimonial'),
        ),
        migrations.AlterField(
            model_name='itemconciliacao',
            name='conciliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='inventario.conciliacaoua', verbose_name='Conciliação'),
        ),
        migrations.AlterField(
            model_name='ocorrenciaconciliacao',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='inventario.itemconciliacao', verbose_name='Item de Conciliação'),
        ),
        migrations.AddIndex(
            model_name='itemconciliacao',
            index=models.Index(fields=['conciliacao', 'bem'], name='inventario__concili_157e4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='conciliacaoua',
            constraint=models.UniqueConstraint(fields=('unidade_administrativa', 'tipo', 'periodo_final'), name='uniq_conciliacao_ua_tipo_periodo_final'),
        ),
        migrations.AddConstraint(
            model_name='parametroconciliacaoanual',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('ano_referencia',), name='unique_parametro_conciliacao_anual_ativo_por_ano'),
        ),
    ]
