# Generated by Django 4.1.3 on 2026-01-03 18:15
from datetime import date
from django.db import migrations
import re


def preencher_periodo_final_anuais(apps, schema_editor):
    ConciliacaoUA = apps.get_model("inventario", "ConciliacaoUA")

    anuais = ConciliacaoUA.objects.filter(
        tipo="anual",
        periodo_final__isnull=True,
    )

    for conciliacao in anuais:
        ano_referencia = None

        if conciliacao.numero_conciliacao:
            match = re.search(r"/(\d{4})$", conciliacao.numero_conciliacao)
            if match:
                ano_referencia = int(match.group(1))

        if not ano_referencia:
            ano_referencia = conciliacao.criado_em.year - 1

        conciliacao.periodo_final = date(ano_referencia, 12, 31)
        conciliacao.save(update_fields=["periodo_final"])


def reverter_periodo_final_anuais(apps, schema_editor):
    ConciliacaoUA = apps.get_model("inventario", "ConciliacaoUA")

    ConciliacaoUA.objects.filter(
        tipo="anual",
    ).update(periodo_final=None)


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_conciliacaoua_options_and_more'),
    ]

    operations = [
        migrations.RunPython(
            preencher_periodo_final_anuais,
            reverter_periodo_final_anuais,
        ),
    ]
