# Generated by Django 4.1.3 on 2026-01-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_preencher_periodo_final_anuais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conciliacaoua',
            options={'ordering': ['-criado_em', 'unidade_administrativa'], 'verbose_name': 'Conciliação', 'verbose_name_plural': 'Conciliações'},
        ),
        migrations.AlterField(
            model_name='conciliacaoua',
            name='status',
            field=models.CharField(choices=[('em_aberto', 'Aberta'), ('fechado', 'Fechada')], default='em_aberto', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='parametroconciliacaoanual',
            name='periodo_final',
            field=models.DateField(help_text='Data final em que conciliações anuais podem ser criadas/fechadas.', verbose_name='Período Final Permitido'),
        ),
        migrations.AlterField(
            model_name='parametroconciliacaoanual',
            name='periodo_inicial',
            field=models.DateField(help_text='Data inicial em que conciliações anuais podem ser criadas/fechadas.', verbose_name='Período Inicial Permitido'),
        ),
    ]
