# Generated by Django 4.1.3 on 2026-01-05 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0012_alter_conciliacaoua_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conciliacaoua',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conciliacoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='conciliacaoua',
            name='periodo_final',
            field=models.DateField(blank=True, help_text='Data final do período da conciliação.', null=True, verbose_name='Período Final'),
        ),
        migrations.AlterField(
            model_name='conciliacaoua',
            name='status',
            field=models.CharField(choices=[('em_aberto', 'Aberta'), ('fechado', 'Fechada'), ('fechado_admin', 'Fechado pelo Administrador - Não Conciliado')], default='em_aberto', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='itemconciliacao',
            name='situacao',
            field=models.CharField(choices=[('encontrado_sem_divergencia', 'Encontrado sem divergência'), ('encontrado', 'Encontrado'), ('nao_encontrado', 'Não encontrado'), ('divergente', 'Divergente'), ('baixa_fisica', 'Baixa Física')], default='encontrado_sem_divergencia', help_text='Situação do bem no momento da criação da conciliação', max_length=30, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='parametroconciliacaoanual',
            name='ano_referencia',
            field=models.PositiveSmallIntegerField(help_text='Ano da conciliação anual ao qual este parâmetro se refere (ex.: 2025).', verbose_name='Ano de Referência'),
        ),
    ]
