# Generated by Django 4.1.3 on 2026-01-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_alter_conciliacaoua_criado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conciliacaoua',
            name='numero_conciliacao',
            field=models.CharField(help_text='Formato: 001.XXXX/AAAA (anual) ou 001.XXXX/AAAA/VVV (eventual)', max_length=30, verbose_name='Número do Conciliação'),
        ),
    ]
