# Generated by Django 4.1.3 on 2026-01-20
from django.db import migrations


def migrar_baixa_fisica_para_em_processo_em_aberto(apps, schema_editor):
    conciliacao_ua_model = apps.get_model("inventario", "ConciliacaoUA")
    item_conciliacao_model = apps.get_model("inventario", "ItemConciliacao")
    ocorrencia_conciliacao_model = apps.get_model("inventario", "OcorrenciaConciliacao")
    bem_patrimonial_model = apps.get_model("bem_patrimonial", "BemPatrimonial")

    # valores fixos (migration-safe)
    CONCILIACAO_EM_ABERTO = "em_aberto"
    BAIXA_FISICA = "baixa_fisica"
    EM_PROCESSO = "em_processo_de_baixa_fisica"
    NAO_ENCONTRADO = "nao_encontrado"

    conciliacoes_abertas = conciliacao_ua_model.objects.filter(status=CONCILIACAO_EM_ABERTO)

    if not conciliacoes_abertas.exists():
        return

    # ========= 1) Identifica bens afetados =========
    bem_ids_itens = set(
        item_conciliacao_model.objects.filter(
            conciliacao__in=conciliacoes_abertas,
            situacao=BAIXA_FISICA,
        ).values_list("bem_id", flat=True)
    )

    bem_ids_ocorrencias = set(
        ocorrencia_conciliacao_model.objects.filter(
            item__conciliacao__in=conciliacoes_abertas,
            situacao=BAIXA_FISICA,
        ).values_list("item__bem_id", flat=True)
    )

    bem_ids_afetados = list(bem_ids_itens.union(bem_ids_ocorrencias))

    # ========= 2) Migra ocorrências =========
    ocorrencia_conciliacao_model.objects.filter(
        item__conciliacao__in=conciliacoes_abertas,
        situacao=BAIXA_FISICA,
    ).update(situacao=EM_PROCESSO)

    # ========= 3) Migra snapshot do item =========
    item_conciliacao_model.objects.filter(
        conciliacao__in=conciliacoes_abertas,
        situacao=BAIXA_FISICA,
    ).update(situacao=EM_PROCESSO)

    # ========= 4) Recalcula bloqueio dos bens (equivalente ao helper) =========
    if bem_ids_afetados:
        bem_ids_bloquear = set(
            item_conciliacao_model.objects.filter(
                bem_id__in=bem_ids_afetados,
                conciliacao__status=CONCILIACAO_EM_ABERTO,
                situacao__in=[NAO_ENCONTRADO, EM_PROCESSO],
            ).values_list("bem_id", flat=True)
        )

        # bloqueia
        if bem_ids_bloquear:
            bem_patrimonial_model.objects.filter(pk__in=bem_ids_bloquear).update(
                bloqueado_conciliacao=True
            )

        # desbloqueia o restante do escopo
        bem_ids_desbloquear = set(bem_ids_afetados) - bem_ids_bloquear
        if bem_ids_desbloquear:
            bem_patrimonial_model.objects.filter(pk__in=bem_ids_desbloquear).update(
                bloqueado_conciliacao=False
            )

        # se o bem já estiver BAIXA_FISICA definitiva, não mantém bloqueio por inventário
        bem_patrimonial_model.objects.filter(
            pk__in=bem_ids_afetados,
            status=BAIXA_FISICA,
        ).update(bloqueado_conciliacao=False)


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0014_alter_conciliacaoua_numero_conciliacao"),
    ]

    operations = [
        migrations.RunPython(
            migrar_baixa_fisica_para_em_processo_em_aberto,
            migrations.RunPython.noop,  # correção definitiva de regra de negócio
        ),
    ]
