# Generated by Django 4.1.3 on 2026-01-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_migrar_baixa_fisica_em_aberto_para_em_processo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemconciliacao',
            name='situacao',
            field=models.CharField(choices=[('encontrado_sem_divergencia', 'Encontrado sem divergência'), ('encontrado', 'Encontrado'), ('nao_encontrado', 'Não encontrado'), ('divergente', 'Divergente'), ('em_processo_de_baixa_fisica', 'Em processo de baixa'), ('baixa_fisica', 'Baixa Física')], default='encontrado_sem_divergencia', help_text='Situação do bem no momento da criação da conciliação', max_length=30, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='ocorrenciaconciliacao',
            name='situacao',
            field=models.CharField(choices=[('encontrado_sem_divergencia', 'Encontrado sem divergência'), ('encontrado', 'Encontrado'), ('nao_encontrado', 'Não encontrado'), ('divergente', 'Divergente'), ('em_processo_de_baixa_fisica', 'Em processo de baixa'), ('baixa_fisica', 'Baixa Física')], default='divergente', help_text='Situação na ocorrencia', max_length=30, verbose_name='Situação'),
        ),
    ]
