# Generated by Django 4.1.3 on 2025-10-07 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rf',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='RF deve conter apenas números.', regex='^\\d+$')], verbose_name='RF'),
        ),
    ]
