# Generated by Django 4.1.3 on 2025-10-15 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0002_alter_unidadeadministrativa_options'),
        ('usuario', '0002_usuario_rf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='unidade_administrativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_unidade_administrativa', to='dados_comuns.unidadeadministrativa'),
        ),
    ]
