# Generated by Django 4.1.3 on 2025-10-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
