# Generated by Django 4.1.3 on 2026-02-03 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_usuario_unidade_orcamentaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rf',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='RF deve começar com uma letra e conter apenas números após ela. Ex: F53399 ou f53399.', regex='^[A-Za-z][0-9]+$')], verbose_name='RF'),
        ),
    ]
