# Generated by Django 4.1.3 on 2026-02-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dados_comuns", "0009_unidadeorcamentaria_sigla_and_more"),
        ("usuario", "0008_alter_usuario_rf"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="unidades_administrativas",
            field=models.ManyToManyField(
                blank=True,
                related_name="operadores",
                to="dados_comuns.unidadeadministrativa",
                verbose_name="Unidades Administrativas permitidas",
            ),
        ),
    ]
