# Generated by Django 4.1.3 on 2023-03-06 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendada', models.DateField(verbose_name='Data')),
                ('hora_agendada', models.TimeField(verbose_name='Hora')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observacao')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'agendamento de suporte',
                'verbose_name_plural': 'agendamentos de suporte',
            },
        ),
        migrations.CreateModel(
            name='ConfigAgendaSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'configuração de agenda',
                'verbose_name_plural': 'configuração de agenda',
            },
        ),
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveIntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Dia da semana')),
                ('agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamento_suporte.configagendasuporte', verbose_name='Agenda')),
            ],
            options={
                'verbose_name': 'dia da semana',
                'verbose_name_plural': 'dias da semana',
            },
        ),
        migrations.CreateModel(
            name='IntervaloHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Hora início')),
                ('hora_fim', models.TimeField(verbose_name='Hora fim')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento_suporte.diasemana', verbose_name='Agenda suporte')),
            ],
            options={
                'verbose_name': 'intervalo de horas',
                'verbose_name_plural': 'intervalos de horas',
            },
        ),
    ]
