# Generated by Django 4.1.3 on 2023-03-15 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigAgendaSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'configuração de agenda',
                'verbose_name_plural': 'configuração de agenda',
            },
        ),
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=30, verbose_name='Dia da semana')),
                ('agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamento_suporte.configagendasuporte', verbose_name='Agenda')),
            ],
            options={
                'verbose_name': 'dia da semana',
                'verbose_name_plural': 'dias da semana',
                'unique_together': {('dia_semana', 'agenda')},
            },
        ),
        migrations.CreateModel(
            name='IntervaloHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Hora início')),
                ('hora_fim', models.TimeField(verbose_name='Hora fim')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento_suporte.diasemana', verbose_name='Agenda suporte')),
            ],
            options={
                'verbose_name': 'intervalo de horas',
                'verbose_name_plural': 'intervalos de horas',
            },
        ),
        migrations.CreateModel(
            name='AgendamentoSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendada', models.DateField(verbose_name='Data')),
                ('hora_agendada', models.TimeField(verbose_name='Hora')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observacao')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('agendado_por', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Agendado por')),
            ],
            options={
                'verbose_name': 'agendamento de suporte',
                'verbose_name_plural': 'agendamentos de suporte',
            },
        ),
    ]
