# Generated by Django 4.1.3 on 2023-03-06 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agendamento_suporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentosuporte',
            name='agendado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Agendado por'),
        ),
        migrations.AlterUniqueTogether(
            name='diasemana',
            unique_together={('dia_semana', 'agenda')},
        ),
    ]
