# Generated by Django 4.1.3 on 2025-10-15 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dados_comuns", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unidadeadministrativa",
            options={
                "ordering": ["codigo", "nome", "sigla"],
                "verbose_name": "unidade administrativa",
                "verbose_name_plural": "unidades administrativas",
            },
        ),
    ]
