# Generated by Django 4.1.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dados_comuns", "0002_alter_unidadeadministrativa_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadeadministrativa",
            name="status",
            field=models.CharField(
                choices=[("ativa", "Ativa"), ("inativa", "Inativa")],
                default="ativa",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
