# Generated by Django 4.1.3 on 2025-10-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0003_unidadeadministrativa_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadeadministrativa',
            options={'ordering': ['codigo', 'sigla', 'nome'], 'verbose_name': 'unidade administrativa', 'verbose_name_plural': 'unidades administrativas'},
        ),
    ]
