# Generated by Django 4.1.3 on 2025-10-31 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dados_comuns', '0004_alter_unidadeadministrativa_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('campo', models.CharField(max_length=128, verbose_name='Campo alterado')),
                ('valor_antigo', models.TextField(blank=True, null=True, verbose_name='Valor antigo')),
                ('valor_novo', models.TextField(blank=True, null=True, verbose_name='Valor novo')),
                ('alterado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Alterado em')),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'histórico geral',
                'verbose_name_plural': 'histórico geral',
                'ordering': ('-alterado_em', 'content_type', 'object_id'),
            },
        ),
        migrations.AddIndex(
            model_name='historicogeral',
            index=models.Index(fields=['content_type', 'object_id', 'alterado_em'], name='dados_comun_content_30d77c_idx'),
        ),
    ]
