# Generated by Django 4.1.3 on 2026-02-03 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0008_tornar_uo_obrigatoria_em_ua'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadeorcamentaria',
            name='sigla',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='sigla'),
        ),
        migrations.AlterField(
            model_name='unidadeadministrativa',
            name='unidade_orcamentaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades_administrativas', to='dados_comuns.unidadeorcamentaria', verbose_name='Unidade Orçamentária'),
        ),
    ]
