# Generated by Django 4.1.3 on 2026-02-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_comuns', '0009_unidadeorcamentaria_sigla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicogeral',
            name='justificativa',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa'),
        ),
        migrations.AlterField(
            model_name='historicogeral',
            name='valor_antigo',
            field=models.TextField(blank=True, default='', verbose_name='Valor antigo'),
        ),
        migrations.AlterField(
            model_name='historicogeral',
            name='valor_novo',
            field=models.TextField(blank=True, default='', verbose_name='Valor novo'),
        ),
        migrations.AlterField(
            model_name='unidadeorcamentaria',
            name='sigla',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='sigla'),
        ),
    ]
